#' Generate Correlation Plot and Matrix for Raster Layers
#'
#' Calculates and plots the correlation matrix for a sample of cell values
#' from a multi-layer SpatRaster. It helps visualize collinearity among predictors.
#' Note that correlations are calculated based on a sample of cells (up to 5000)
#' for efficiency.
#'
#' @param rasterLayers A terra `SpatRaster` object with multiple layers (predictors).
#'
#' @return A `list` containing two elements:
#'   \item{plot}{The correlation plot object generated by `corrplot::corrplot`.}
#'   \item{correlationPairs}{The numeric correlation matrix calculated using `stats::cor`.}
#' @export
#' @importFrom terra as.data.frame
#' @importFrom stats cor na.omit
#' @importFrom corrplot corrplot
#'
#' @examples
#' \dontrun{
#' # Create an example multi-layer SpatRaster
#' r1 <- terra::rast(nrows=10, ncols=10, vals=rnorm(100))
#' r2 <- r1 * 1.5 + rnorm(100, 0, 0.5)
#' r3 <- terra::rast(nrows=10, ncols=10, vals=runif(100))
#' my_rasters <- c(r1, r2, r3)
#' names(my_rasters) <- c("Var1", "Var2", "Var3")
#'
#' # Get the correlation plot and matrix
#' corr_info <- getCorrPlot(my_rasters)
#'
#' # To display the plot (might need explicit print in some contexts)
#' # print(corr_info$plot)
#' # View the correlation matrix
#' print(corr_info$correlationPairs)
#' }
getCorrPlot <- function(rasterLayers) {

  # Convert raster to data frame, keeping non-NA cells only implicitly via cor
  # Note: as.data.frame(..., na.rm=TRUE) is not an argument,
  # na.rm happens during sampling or cor calculation
  rasterLayersDF <- terra::as.data.frame(rasterLayers, na.rm = FALSE) # Get all cells first
  rasterLayersDF <- stats::na.omit(rasterLayersDF) # Remove rows with any NAs

  # Sample cells if the raster is large
  n_total_cells <- nrow(rasterLayersDF)
  sample_size <- min(c(5000, n_total_cells))
  sampled_indices <- sample(1:n_total_cells, sample_size, replace = FALSE)
  rasterLayersDF_sampled <- rasterLayersDF[sampled_indices, ]

  # Calculate correlation matrix
  cor_matrix <- stats::cor(rasterLayersDF_sampled)

  # Create the correlation plot
  # Explicitly call corrplot::corrplot for clarity, even though imported
  corr_plot <- corrplot::corrplot(cor_matrix, type = "upper", diag = FALSE)

  # Return both the plot object (though plotting happens immediately usually)
  # and the correlation matrix
  return(list(plot = corr_plot, correlationPairs = cor_matrix))

}
