#' Calculate and Plot Variable Importance from Model Ensemble
#'
#' Extracts or calculates variable importance scores from a list of fitted model
#' objects (typically generated by `trainModel`). It calculates the mean and
#' standard error of importance across the ensemble and generates a bar plot.
#' Note: Importance metrics are algorithm-specific (e.g., relative influence for
#' GBM, Gain for XGBoost, absolute coefficient for GLM). Maxent importance is not
#' calculated by this function (requires permutation).
#'
#' @export
#' @importFrom stats sd reorder na.omit coefficients # For GLM coefs and plotting/stats
#' @importFrom ggplot2 ggplot aes geom_bar geom_errorbar coord_flip theme_bw theme element_text element_blank element_line labs geom_hline annotate position_dodge ggplotGrob is.ggplot # For plotting
#' @importFrom gbm summary.gbm # Necessary for summary method for gbm objects
#' @importFrom xgboost xgb.importance # For xgboost importance
#' @importFrom methods is
#'

variableContribution <- function(models,rasterLayers) {

  algorithmModels <- models$model

  algorithmType <- class(algorithmModels[[1]])[1]
  relativeImportanceMatrix <- matrix(NA,ncol=length(algorithmModels),nrow=nlyr(rasterLayers))

  if( algorithmType == "gbm" ) {
    for(m in 1:length(algorithmModels)) {
      relativeImportance.m <- summary(algorithmModels[[m]], plotit = TRUE)
      relativeImportanceMatrix[,m] <- relativeImportance.m[match(names(rasterLayers),relativeImportance.m$var),"rel.inf"]
    }
    relativeImportance <- data.frame(Predictor=names(rasterLayers),relImportance=apply(relativeImportanceMatrix,1,mean,na.rm=T),relImportance.sd=apply(relativeImportanceMatrix,1,sd,na.rm=T))
    relativeImportance[is.na(relativeImportance)] <- 0
  }

  if(algorithmType == "mboost") {
    for(m in 1:length(algorithmModels)) {
      relativeImportanceMatrix[,m] <- sapply(1:nlyr(rasterLayers), function(x) { res <- varimp(algorithmModels[[m]])[which(grepl(names(rasterLayers)[x],names(varimp(algorithmModels[[m]]))))]; ifelse(length(res)>0,res,NA) } )
    }
    relativeImportanceMatrix[is.na(relativeImportanceMatrix)] <- 0
    relativeImportance <- data.frame(Predictor=names(rasterLayers),relImportance=apply(relativeImportanceMatrix,1,mean,na.rm=T),relImportance.sd=apply(relativeImportanceMatrix,1,sd,na.rm=T))
    relativeImportance$relImportance <- ((relativeImportance$relImportance - min(relativeImportance$relImportance) ) / sum(relativeImportance$relImportance) ) * 100
    relativeImportance$relImportance.sd <-  relativeImportance$relImportance.sd * 100
  }

  if(algorithmType == "xgb.Booster") {
    for(m in 1:length(algorithmModels)) {
      relativeImportance.m = as.data.frame(xgb.importance(algorithmModels[[m]]$feature_names, model = algorithmModels[[m]])[,1:2])
      relativeImportanceMatrix[,m] <- relativeImportance.m[match(names(rasterLayers),relativeImportance.m$Feature),"Gain"]
    }
    relativeImportance <- data.frame(Predictor=names(rasterLayers),relImportance=apply(relativeImportanceMatrix,1,mean,na.rm=T),relImportance.sd=apply(relativeImportanceMatrix,1,sd,na.rm=T))
    relativeImportance[is.na(relativeImportance)] <- 0
    relativeImportance$relImportance <- ( (relativeImportance$relImportance ) / sum(relativeImportance$relImportance) ) * 100
    relativeImportance$relImportance.sd <-  relativeImportance$relImportance.sd * 100
  }

  ## ----------

  relativeImportance$relImportance.sd <- relativeImportance$relImportance.sd / sqrt(length(model$model))

  relativeImportancePlot <- ggplot(data=relativeImportance[sort(relativeImportance[,2],decreasing = TRUE,index.return=TRUE)$ix,]) +
    geom_bar( aes(x= reorder(Predictor, relImportance) , y=relImportance), stat="identity", fill="#ffd45b", alpha=0.85) +
    geom_errorbar( aes(x= reorder(Predictor, relImportance), ymin=relImportance-ifelse(relImportance.sd == 0, NA, relImportance.sd), ymax=relImportance+ifelse(relImportance.sd == 0, NA, relImportance.sd)), width=.1, alpha=0.8, size=0.4, position=position_dodge(.9))  +
    coord_flip() +
    theme_bw() +
    theme(
      axis.text=element_text(size=10),
      axis.title.x = element_text(margin = margin(t = 10, r = 0, b = 0, l = 0) , size=13.5),
      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0) , size=13.5),
      panel.border = element_blank(),
      panel.background = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.major = element_line(linewidth = 0.25, linetype = 'solid',colour = "#EFEFEF"),
      panel.grid.minor = element_line(linewidth = 0, linetype = 'solid',colour = "#EFEFEF")
    ) + labs(x = "") +
    labs(y = "Relative importance (%)") + geom_hline(aes(yintercept=5 ),color="Black", linetype="dashed", size=0.3) +
    annotate("text", y = 5 + 1 , x = 1 , label = "5%" , hjust = 0) + geom_hline(aes(yintercept=0 ),color="Gray", size=0.3)

  relativeContribution <- list(dataFrame=relativeImportance,plot=relativeImportancePlot)
  return(relativeContribution)

}

